-- migration-03

CREATE TABLE IF NOT EXISTS ingredients(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  recipe_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  amount DECIMAL(5, 3) NOT NULL,
  measurement TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (recipe_id) REFERENCES recipes (id) ON DELETE CASCADE
);
